train:
  _target_: src.datasets.ASVSpoofDataset
  flac_dir_path: "../data/LA/LA/ASVspoof2019_LA_train"
  protocol_path: "../data/LA/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt"
  instance_transforms: ${transforms.instance_transforms.train} 
val:
  _target_: src.datasets.ASVSpoofDataset
  flac_dir_path: "../data/LA/LA/ASVspoof2019_LA_eval"
  protocol_path: "../data/LA/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt"
  instance_transforms: ${transforms.instance_transforms.inference}
