defaults:
  - model: lightcnn
  - writer: wandb
  - metrics: ce_eer
  - datasets: asvspoof
  - dataloader: example
  - transforms: trimpad
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4
  # The other parameters from papers are actually torch defaults
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.5
  step_size: 30000  # Approximation of 10 epochs for our dataset
loss_function:
  _target_: src.loss.ExampleLoss  # Already cross-entropy
trainer:
  log_step: 50
  n_epochs: 10
  epoch_len: null
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: False # if True, will override the previous run with the same name
  monitor: "min val_eval_EER" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
