defaults:
  - model: lightcnn
  - metrics: ce_eer
  - datasets: asvspoof
  - dataloader: example
  - transforms: trimpad
  - _self_
inferencer:
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "lightcnn-fixed-results" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/lightcnn-fixed/model_best.pth" # path to the pretrained model
